<?php

namespace Test\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SheetRepository extends EntityRepository
{
    public function getAll()
    {
        $dq=$this->createQueryBuilder('s');
        $query=$dq;
        $result=$query->getQuery()->execute();
        return $result ;

    }
}
